class DataManager {
  static List<dynamic> allDates;
  static List<dynamic> dailyData;
  static List<dynamic> hospitalData;
  static List<dynamic> seoulHospitalData;
  static List<dynamic> busanHospitalData;
  static List<dynamic> daeguHospitalData;
  static List<dynamic> incheonHospitalData;
  static List<dynamic> gwangjuHospitalData;
  static List<dynamic> daejeonHospitalData;
  static List<dynamic> ulsanHospitalData;
  static List<dynamic> sejongHospitalData;
  static List<dynamic> gyeonggiHospitalData;
  static List<dynamic> gangwonHospitalData;
  static List<dynamic> chungbukHospitalData;
  static List<dynamic> chungnamHospitalData;
  static List<dynamic> jeonbukHospitalData;
  static List<dynamic> jeonnamHospitalData;
  static List<dynamic> kyeongbukHospitalData;
  static List<dynamic> kyeongnamHospitalData;
  static List<dynamic> jejuHospitalData;
}