class DataManager {
  static List<dynamic> allDates;
  static List<dynamic> dailyData;
  static List<dynamic> hospitalData;
  static List<dynamic> seoulHospitalData;
  static List<dynamic> busanHospitalData;
  static List<dynamic> daeguHospitalData;
  static List<dynamic> incheonHospitalData;
  static List<dynamic> gwangjuHospitalData;
  static List<dynamic> daejeonHospitalData;
  static List<dynamic> ulsanHospitalData;
  static List<dynamic> sejongHospitalData;
  static List<dynamic> gyeonggiHospitalData;
  static List<dynamic> gangwonHospitalData;
  static List<dynamic> chungbukHospitalData;
  static List<dynamic> chungnamHospitalData;
  static List<dynamic> jeonbukHospitalData;
  static List<dynamic> jeonnamHospitalData;
  static List<dynamic> kyeongbukHospitalData;
  static List<dynamic> kyeongnamHospitalData;
  static List<dynamic> jejuHospitalData;
  // static List<dynamic> seoulHospitalData = new List<dynamic>();
  // static List<dynamic> busanHospitalData = new List<dynamic>();
  // static List<dynamic> daeguHospitalData = new List<dynamic>();
  // static List<dynamic> incheonHospitalData = new List<dynamic>();
  // static List<dynamic> gwangjuHospitalData = new List<dynamic>();
  // static List<dynamic> daejeonHospitalData = new List<dynamic>();
  // static List<dynamic> ulsanHospitalData = new List<dynamic>();
  // static List<dynamic> sejongHospitalData = new List<dynamic>();
  // static List<dynamic> gyeonggiHospitalData = new List<dynamic>();
  // static List<dynamic> gangwonHospitalData = new List<dynamic>();
  // static List<dynamic> chungbukHospitalData = new List<dynamic>();
  // static List<dynamic> chungnamHospitalData = new List<dynamic>();
  // static List<dynamic> jeonbukHospitalData = new List<dynamic>();
  // static List<dynamic> jeonnamHospitalData = new List<dynamic>();
  // static List<dynamic> kyeongbukHospitalData = new List<dynamic>();
  // static List<dynamic> kyeongnamHospitalData = new List<dynamic>();
  // static List<dynamic> jejuHospitalData = new List<dynamic>();
}